-- Schéma H2 pour les tests unitaires rapides
-- Equivalent fonctionnel de V1 + V2, adapté aux mots-clés réservés H2
-- Colonnes renommées : key→meta_key, value→meta_value (mots réservés H2)

CREATE TABLE IF NOT EXISTS stations (
    id    VARCHAR(255) PRIMARY KEY,
    name  VARCHAR(255) NOT NULL,
    lat   DOUBLE PRECISION,
    lon   DOUBLE PRECISION,
    mode  VARCHAR(50)  NOT NULL DEFAULT 'TRAIN'
);

CREATE TABLE IF NOT EXISTS station_aliases (
    station_id  VARCHAR(255) NOT NULL,
    alias       VARCHAR(255) NOT NULL,
    PRIMARY KEY (station_id, alias)
);

CREATE TABLE IF NOT EXISTS routes (
    id          VARCHAR(255) PRIMARY KEY,
    short_name  VARCHAR(255),
    long_name   VARCHAR(255),
    mode        VARCHAR(50)  NOT NULL DEFAULT 'TRAIN'
);

CREATE TABLE IF NOT EXISTS trips (
    id          VARCHAR(255) PRIMARY KEY,
    route_id    VARCHAR(255) NOT NULL,
    service_id  VARCHAR(255) NOT NULL,
    headsign    VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS stop_times (
    trip_id            VARCHAR(255) NOT NULL,
    stop_id            VARCHAR(255) NOT NULL,
    stop_sequence      INTEGER      NOT NULL,
    departure_seconds  INTEGER      NOT NULL,
    arrival_seconds    INTEGER      NOT NULL,
    PRIMARY KEY (trip_id, stop_sequence)
);

CREATE INDEX IF NOT EXISTS idx_st_stop     ON stop_times(stop_id);
CREATE INDEX IF NOT EXISTS idx_st_trip     ON stop_times(trip_id);
CREATE INDEX IF NOT EXISTS idx_st_stop_dep ON stop_times(stop_id, departure_seconds);

CREATE TABLE IF NOT EXISTS calendar (
    service_id  VARCHAR(255) PRIMARY KEY,
    monday      SMALLINT     NOT NULL,
    tuesday     SMALLINT     NOT NULL,
    wednesday   SMALLINT     NOT NULL,
    thursday    SMALLINT     NOT NULL,
    friday      SMALLINT     NOT NULL,
    saturday    SMALLINT     NOT NULL,
    sunday      SMALLINT     NOT NULL,
    start_date  VARCHAR(10)  NOT NULL,
    end_date    VARCHAR(10)  NOT NULL
);

CREATE TABLE IF NOT EXISTS calendar_dates (
    service_id      VARCHAR(255) NOT NULL,
    date            VARCHAR(10)  NOT NULL,
    exception_type  SMALLINT     NOT NULL,
    PRIMARY KEY (service_id, date)
);

CREATE TABLE IF NOT EXISTS fares (
    route_id    VARCHAR(255) NOT NULL,
    from_stop   VARCHAR(255) NOT NULL,
    to_stop     VARCHAR(255) NOT NULL,
    fare_mad    DOUBLE PRECISION NOT NULL,
    fare_class  VARCHAR(50),
    PRIMARY KEY (route_id, from_stop, to_stop)
);

-- Colonnes renommées pour éviter les conflits avec mots réservés H2
-- (key et value sont réservés dans H2 même en MODE=PostgreSQL)
-- IMPORTANT : adapter StoreRepository si ce nom change
CREATE TABLE IF NOT EXISTS ingestion_meta (
    meta_key    VARCHAR(255) PRIMARY KEY,
    meta_value  TEXT         NOT NULL
);

-- Perturbations temps réel (simplifié pour H2)
CREATE TABLE IF NOT EXISTS disruptions (
    id           BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    route_id     VARCHAR(255),
    stop_id      VARCHAR(255),
    type         VARCHAR(50)  NOT NULL,
    severity     VARCHAR(50)  NOT NULL,
    description  TEXT         NOT NULL,
    starts_at    TIMESTAMP,
    ends_at      TIMESTAMP,
    created_at   TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    source       VARCHAR(255)
);

CREATE INDEX IF NOT EXISTS idx_disruptions_route  ON disruptions(route_id);
CREATE INDEX IF NOT EXISTS idx_disruptions_stop   ON disruptions(stop_id);
CREATE INDEX IF NOT EXISTS idx_disruptions_active ON disruptions(starts_at, ends_at);

-- V4: corrections table (same structure, H2-compatible)
CREATE TABLE IF NOT EXISTS corrections (
    id            BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type          VARCHAR(50)  NOT NULL,
    description   TEXT         NOT NULL,
    data_source   VARCHAR(255),
    submitted_at  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    status        VARCHAR(20)  NOT NULL DEFAULT 'PENDING'
);
