-- V2__add_disruptions.sql
-- Table des perturbations temps réel (retards, suppressions, déviations)
-- Compatible H2 (MODE=PostgreSQL) et PostgreSQL 16.

CREATE TABLE IF NOT EXISTS disruptions (
    id           BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    route_id     VARCHAR(255),
    stop_id      VARCHAR(255),
    type         VARCHAR(50)  NOT NULL,   -- DELAY | CANCELLATION | DIVERSION
    severity     VARCHAR(50)  NOT NULL,   -- LOW | MEDIUM | HIGH
    description  TEXT         NOT NULL,
    starts_at    TIMESTAMP,
    ends_at      TIMESTAMP,
    created_at   TIMESTAMP    NOT NULL    DEFAULT CURRENT_TIMESTAMP,
    source       VARCHAR(255)
);

CREATE INDEX IF NOT EXISTS idx_disruptions_route    ON disruptions(route_id);
CREATE INDEX IF NOT EXISTS idx_disruptions_stop     ON disruptions(stop_id);
-- Index pour requête "perturbations actives à l'instant T"
CREATE INDEX IF NOT EXISTS idx_disruptions_active   ON disruptions(starts_at, ends_at);
