-- V4__add_corrections.sql
-- Table for crowd-sourced data corrections (Lot 3: submit_correction tool).
-- Full correction workflow (moderation, grand-taxi routes) comes in Lot 5.

CREATE TABLE IF NOT EXISTS corrections (
    id            BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type          VARCHAR(50)  NOT NULL,  -- FARE | ROUTE | STATION | SCHEDULE | OTHER
    description   TEXT         NOT NULL,
    data_source   VARCHAR(255),           -- optional: which station/route/stop is concerned
    submitted_at  TIMESTAMP    NOT NULL   DEFAULT CURRENT_TIMESTAMP,
    status        VARCHAR(20)  NOT NULL   DEFAULT 'PENDING'  -- PENDING | REVIEWED | APPLIED
);

CREATE INDEX IF NOT EXISTS idx_corrections_status ON corrections(status);
CREATE INDEX IF NOT EXISTS idx_corrections_type   ON corrections(type);
